### ISSUE TITLE
Lightning Intent Handling

### ISSUE THREAD

**Issue by jackeveritt** [muun/apollo#1]
Can you support paying lightning invoices via a deep link/app link?  It doesnt seem to support open links from external sources?

We have an android app that lets the user open external wallets with a link to the intent scheme:

lightning:<invoice>

Here is a link to a video of it working with Eclair:

https://youtu.be/Vs1NBqm-DGc

I can confirm BlueWallet, Wallet of Satoshi, Zap and Breez also use this uri scheme.

Here's an example of a commit that BlueWallet did recently to fix their lightning url handle after it broke: https://github.com/BlueWallet/BlueWallet/commit/cfd2c3d310e1cb38af42bbed4329e03b5a6937de

**Comment by esneider** [comment]
Definitely! Great feature request.

I'll let you know once we release it.

**Comment by esneider** [comment]
@jackeveritt we just added support for lightning URI intents! Give it a try and let us know if you have any other feedback or suggestions.
