### ISSUE TITLE
[proposal] Muun version that will work without Google Services

### ISSUE THREAD

**Issue by TheFuzzStone** [muun/apollo#104]
Make it possible to use Muun Wallet without having ~~malware/spyware~~ Google Services.

---

![image](https://user-images.githubusercontent.com/16173361/211478507-1618db97-29a8-4559-a231-7b34ae54caed.png)

---

Even when I skipped the previous popup about not having Google Services, the wallet still didn't generate. Personally, this seems like a strange decision from the developers.

![image](https://user-images.githubusercontent.com/16173361/211479519-1e8dc45c-de61-4733-9764-d61915f4caa3.png)

**Comment by acrespo** [comment]
Hi there!

Thank you for taking the time to give us your feedback! We really appreciate it. 

Would you mind checking out https://github.com/muun/apollo/issues/9, adding your thoughts there and closing this issue? We'd like to keep the conversation on one place.

**Comment by TheFuzzStone** [comment]
Closing the issue because of #9.
