### ISSUE TITLE
[Feature Request]: Display amount value in "Main currency" on the "Send bitcoin" form

### ISSUE THREAD

**Issue by DeckerSU** [muun/apollo#114]
When somebody sends you a Lightning invoice or you scan a Lightning invoice from a QR code, you'll only see the amount in BTC on the "Send Bitcoin" form. This can be confusing, especially for new users who can't determine the approximate fiat amount of the transaction. Currently, you can only see the fiat amount in parentheses in the transaction history, like 0.00004105 BTC (0.93 EUR) after the payment is already sent. To prevent confusion, I suggest adding a display of the same amount in the "Main Currency" (EUR, USD, etc.) on the "Send Bitcoin" form, so users can get an idea of how much they are sending in fiat.

![image](https://user-images.githubusercontent.com/22120003/224873749-bac1214a-100f-438d-a7b8-f2a763bc63ce.png)

Thanks in advance.

**Comment by acrespo** [comment]
Hi there!

Thanks for taking the time and sending us such detailed feedback! We get this sometimes. We're painfully aware that the send screen has some big UI/UX challenges (the screen real state is so scarce 😞).  In the meantime, after selecting an amount and in the final confirmation step, if you tap on any amount, you can switch from BTC to your primary currency. This feature has a discovery problem but could be used to tackle the problem you mention.

**Comment by DeckerSU** [comment]
Thank you for the quick response. Really, exactly as you said, when tapping the amount in BTC on the "Send Bitcoin Form," the amount changes to the selected fiat "Main Currency." It's a hidden UI feature, but it works like a charm. However it reminded me of an Easter egg in Android, where you also have to tap something several times :smiling_face_with_tear:

**Comment by acrespo** [comment]
Closing as feature is already implemented (hehe). We'll definitely work on improving the discovery
