### ISSUE TITLE
Missing sources for latest release 44.3 on google-play

### ISSUE THREAD

**Issue by emanuelb** [muun/apollo#13]
The version in google-play is 44.3, Updated: February 26, 2021
https://play.google.com/store/apps/details?id=io.muun.apollo
while the latest commit in this repo is for previous version 44.2:
https://github.com/muun/apollo/commit/a506d13add1999e3637fb1cac9cb050d8df4df8c
Please improve your source publishing process, to publish it before the apk is uploaded to google-play.

**Comment by acrespo** [comment]
Hi @emanuelb! Sorry about this! And thanks for helping us. The updated version of the source code is now available, see 486180aeefb1abdc9ed6390fbd850fdf4d4ad636. 

We're definitely looking into improving our publishing process. In fact, we are currently changing it as part of our effort to  provide reproducible builds and that may have had something to do with this slipping through the cracks.

Again, thank you for so much, sorry for so little!
