### ISSUE TITLE
Can't the LN address be made smaller?

### ISSUE THREAD

**Issue by Cskhellcsk** [muun/apollo#136]
When I write my LN address on X, it is not accepted because it is too long. 😔

**Comment by Cskhellcsk** [comment]
It's been 3 days and still no answer. Wasn't there any manager who took care of this muun wallet?

**Comment by acrespo** [comment]
Hi there! I'm so sorry for the delay. 

Unfortunately, we do not support [Lightning Address](https://lightningaddress.com/). You're probably copying a LN invoice which is larger than a Lighting Address. Assuming X is expecting a Lightning Address, that's probably the reason of the error you are seeing.

For more information, you can join the conversation in this [other issue ](https://github.com/muun/apollo/issues/53).

**Comment by Cskhellcsk** [comment]
Thank you for your late reply.
