### ISSUE TITLE
Join the Bitcoin Design Community with Global Accessibility Awareness Day

### ISSUE THREAD

**Issue by mouxdesign** [muun/apollo#145]
Hey Muun team,
Over at the Bitcoin Design Community we are participating in Global Accessibility Awareness Day by inviting builders for a quick one hour session with the community to learn about how to test for and improve accessibility. We would be super grateful if one person or a few people from the team could join. We'll keep things very hands on and practical during the session.

It's on the 16th of May at 7:00 UTC. [Event link ](https://github.com/BitcoinDesign/Meta/issues/655)

Also a link here for the page we added to the [Bitcoin Design Guide](https://bitcoin.design/guide/designing-products/accessibility/) about Accessibility.

![303594583-2316b9c3-d6c6-4004-867f-a0a75310f907](https://github.com/muun/apollo/assets/90313394/9468b535-ef14-41e4-a9a2-a5ab4bcec62a)

**Comment by acrespo** [comment]
Hi there!

Sorry for the late response. We're a bit overwhelmed and won't be able to make it. Hopefully we can't make it the next year!
