### ISSUE TITLE
Transaction stuck “confirming”

### ISSUE THREAD

**Issue by crappyguy** [muun/apollo#146]
I have a transaction stuck "Confirming" for several days (iOS) . I set the fees too low. How do I fix this?

**Comment by acrespo** [comment]
Hi there! 

Sorry for the delayed response. Yes, the halving and the launch of the Runes protocol resulted in an unprecedented fee spike. You can read more about this here: https://cointelegraph.com/news/runes-protocol-ignite-new-season-bitcoin-after-halving.  

Please contact us at support@muun.com, we'll be happy to try and help you. You can add a link to this issue in the email.

**Comment by acrespo** [comment]
Hi there! 

Following up on this. Could you write to [support@muun.com](mailto:support@muun.com)? I'm not aware of any contact linking to this issue. 

Closing this for now, as this is not the proper communication channel but please feel free to contact us via email. 

I hope that now that now that fees have decreased your transaction gets confirmed!

Cheers.
