### ISSUE TITLE
Stuck transactions on mempool

### ISSUE THREAD

**Issue by Souljahsmitty** [muun/apollo#151]
What are the steps to cancel or unstuck transactions on mempool. I just learned about this happening because of the low fee amount I did

**Comment by slightlyfaulty** [comment]
Email Muun support, they will help you. This isn't the place to ask about this.

**Comment by acrespo** [comment]
Hi there!

Sorry for the delayed response. As you may already know, currently there is considerable congestion on the Bitcoin network leading to low-fee transactions taking longer to confirm. You can verify this at https://mempool.space/.

Please write to us at [support@muun.com](mailto:support@muun.com) with your transaction ID and we'll be glad to analyze the status of your transaction and possible ways forward.
