### ISSUE TITLE
Posible incompatibilidad con Lightning labs wallet

### ISSUE THREAD

**Issue by GP1992** [muun/apollo#18]
Me apareció este error cuando intenté enviar 10 SAT de prueba a esta wallet.![Screenshot_20210411-003013.png](https://user-images.githubusercontent.com/31271916/114291452-e9cb8f80-9a5d-11eb-95ca-d9936ad6242b.png)

**Comment by champo** [comment]
Hola! Gracias por escribirnos.

Este error en general se muestra cuando no podemos encontrar el nodo al que queres pagar. Esto puede suceder si el nodo no tiene canales publicos o recien los tiene hace poco. Esto esta relacionado con la forma en la que la red distribuye la informacion de nuevos nodos. Si estas dispuesto a compartirnos la informacion de que a que nodo queres pagar puedo revisar a ver que sucede especificamente (puede ser privado escribiendonos a support@muun.com).

Saludos,
Champo

**Comment by GP1992** [comment]
Estoy testeando la compatibilidad de Muun con otras wallet, intente generar un invoice de 100 sat en la wallet de Lightning labs https://github.com/lightninglabs/lightning-app.

Este es el detalle de la orden:
![image](https://user-images.githubusercontent.com/31271916/114905278-2b0dc780-9def-11eb-8c68-007a850c4d54.png)

la direccion de pago es esta lnbc1u1ps8s6y0pp5sa7hqp9duyrkcvj26pguzrvw266trf68mwjrewa2axl9hgux2gwqdq823jhxaqcqzpgxqy9gcqtc42cq369647cdu636wmzkzr6znt8ed37x0jpftx7myunnfw83z3nfxh0m752qyj9chhjdkr09espfvy5fvq4lw3qqmqqgp28dmez9gq7kltla

Ojala sea suficiente. Saludos.

**Comment by esneider** [comment]
@GP1992 esto es porque tu wallet de Lightning Labs no tiene canales, y por lo tanto no se pueden rutear pagos desde Muun, o desde cualquier otra wallet. Tené en cuenta que la wallet de Lightning Labs fue descontinuada y no recibe actualizaciones desde 2019.

Te recomiendo probar con alguna otra wallet que tenga desarrollo activo!
