### ISSUE TITLE
Remove JCenter lines from build.gradle or at least specify what used by it directly

### ISSUE THREAD

**Issue by emanuelb** [muun/apollo#27]
https://github.com/muun/apollo/blob/71e044c98cc72868308e9ebc5fd8a9b7ffd151e1/build.gradle#L7
https://github.com/muun/apollo/blob/71e044c98cc72868308e9ebc5fd8a9b7ffd151e1/build.gradle#L30
https://github.com/muun/apollo/blob/71e044c98cc72868308e9ebc5fd8a9b7ffd151e1/build.gradle#L52

Jcenter service is closed (currently in read-only mode, no updates for packages will be made)
more details on needed migration:
https://developer.android.com/studio/build/jcenter-migration

and here content on how to migrate:
https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

I also suggest to first fixing #26 which make easier to see all deps downloaded by gradle and thus locate the deps that need fixing (contact vendor, etc..) and what versions are used (thus the migration diff will show if dep downgraded in migration which is unlikely but possible if jcenter has newer version then in mavenCentral)

You can declare specific usages of jcenter like explained in https://jeroenmols.com/blog/2021/02/04/migratingjcenter/#consumed-dependencies-from-bintrayjcenter and like it's done for example in this PR of unstoppable wallet "Gradually migrate from jcenter to mavenCentral"
https://github.com/horizontalsystems/unstoppable-wallet-android/pull/3752/files

**Comment by champo** [comment]
Hi, thanks for the detailed report! We've already migrated out of jcenter all of our deps. We seem to have left the reference in the gradle file though. Will remove it first thing Monday.
