### ISSUE TITLE
Reproducible builds ?

### ISSUE THREAD

**Issue by asafyish** [muun/apollo#47]
In the blog post https://blog.muun.com/muuns-new-open-source-model/ in February 1st, you wrote you are working on reproducible builds, is that something you are still working on ?

**Comment by acrespo** [comment]
Yes! Check out https://twitter.com/MuunWallet/status/1379490681165602823

For instructions on:
- How to build reproducibly: https://github.com/muun/apollo/blob/master/BUILD.md#build-reproducibly
- How to verify an existing APK: https://github.com/muun/apollo/blob/master/BUILD.md#verify-an-existing-apk

**Comment by asafyish** [comment]
Thanks !
