### ISSUE TITLE
How can this wallet be self custodial?

### ISSUE THREAD

**Issue by lucaszanella** [muun/apollo#5]
How can I own the sats if I did not fund the channel? Who paid for the funding?

Couldn't find this information on the website

**Comment by esneider** [comment]
Muun will front the cost of the channel open, and you'll pay for it (in lightning fees) as you make outgoing payments later on.

To keep track of this, we use "tiny unidirectional virtual channels" (read more about virtual channels [here](https://www.rene-pickhardt.de/index.html%3Fp=2131.html)). Keeping them unidirectional makes them non-custodial (the client can owe money to the server, but the server can never owe money to the client). Keeping them with only tiny amounts (in the order of on-chain fees) makes sure that there isn't a big fraud risk for the server.

We'll write in more detail about this mechanism soon in our blog!
