### ISSUE TITLE
Add Biometric Fingerprint Recognition

### ISSUE THREAD

**Issue by xmready** [muun/apollo#50]
Would love to see an option for biometric fingerprint unlocking added to this wallet

**Comment by acrespo** [comment]
Hi there! Thanks for the suggestion! Would you mind checking out https://github.com/muun/apollo/issues/45, adding your thoughts there and closing this issue? We'd like to keep the conversation on one place.

**Comment by Petr-Mi** [comment]
Another year passed and no biometric fingerprint recognition :-(
