### ISSUE TITLE
just checking, no bip39 seed phrase, correct?

### ISSUE THREAD

**Issue by petjal** [muun/apollo#57]
Just making sure, there is no bip39 seed phrase with muun, correct?
https://github.com/muun/recovery/issues/1

(Consider enabling github Discussions tab feature for nuub muun questions like this. :)

**Comment by acrespo** [comment]
Hi there!

That is correct! We've talked and written extensively about it. See: https://blog.muun.com/why-not-just-a-mnemonic/.

Bip39 (commonly known as mnemonics) falls short for Muun's use case (a multisig and lightning wallet).

**Comment by petjal** [comment]
wow, great write-up, thanks!
