### ISSUE TITLE
Lebanese Pound LBP

### ISSUE THREAD

**Issue by marcondy** [muun/apollo#7]
Hello, the Lebanese Pound is displayed at an incorrect rate. Due to hyperinflation, our FX rate is different from than officially announced one, 

out community has built API to fix that, taking an average from 3 different sources to avoid manipulation 

https://bitcoinduliban.org/api.php?key=lbpusd

Would greatly appreciate integrating this new rate.

**Comment by champo** [comment]
Hi @marcondy! Thanks for the suggestion. 

We try to get the most representative rates when we can so we'll definitely look into the API you linked. Do you know of any other services that do the same for LBP? Rates are a sensitive topic so we try to have more than one source in case any of them are offline. When that happens users would see their rates jump wildly back to the "official" rate and could cause a lot of pain if someone is in the middle of sending a payment.

**Comment by andrasfuchs** [comment]
I use [EODHistoricalData.com](https://eodhistoricaldata.com/) most of the time, they have both the [USDLBP](https://eodhistoricaldata.com/financial-apis/list-supported-forex-currencies/) and the [BTCUSD](https://eodhistoricaldata.com/financial-apis/list-supported-crypto-currencies/) pairs.

**Comment by marcondy** [comment]
@champo Sorry took me a while to reply, i think i missed out on notifications.

The API i shared isn't available anymore however there is one new open source 

https://yadio.io/api.html

https://api.yadio.io/convert/1/BTC/LBP

**Comment by acrespo** [comment]
Hi there!

We significantly enhanced our handling exchange rates and added support for more accurate exchange rates for several currencies, including the Lebanse Pound (LBP). You can already see this in both Android and iOS apps without needing to update the app. Hope you like it!
