### ISSUE TITLE
UX suggestion

### ISSUE THREAD

**Issue by grunch** [muun/apollo#8]
Hi, first of all congratulations to all the team, I started to use the wallet since you are a full LN wallet and I'm impressed.

I have a UX suggestion, it's not a bug but definitely I think it would give better UX to users with big fingers.

When I am going to send a payment I see this screen

![photo_2021-01-29_15-50-36](https://user-images.githubusercontent.com/228364/106315270-c7d9b380-6249-11eb-887e-ce4906cd6195.jpg)

I changed to SAT and I get this screen

![photo_2021-01-29_15-51-24](https://user-images.githubusercontent.com/228364/106315324-dc1db080-6249-11eb-83a4-bdfa7d9e5948.jpg)

As you can see the keyboard is not being showed, so by intuition I touched the number 0, but nothing happens, I touched again few times and I found out that you need to touch exactly between the 0 and the letters "SAT", then I get the keyboard.

I think for a better UX it would be great to show the keyboard, when the user touches the number or when the user changes the currency.

**Comment by esneider** [comment]
Great catch, thanks!

We are having some trouble making that keyboard behave well, but we'll give it a try.

**Comment by esneider** [comment]
Update on this: we fixed the closed keyboard in most inputs that were hiding it when they shouldn't. Now we are only missing the keyboard after changing the currency.

I'll update here again when we get to it.

**Comment by acrespo** [comment]
Update on this: Apollo 46.6 was release and should have no issues with soft keyboard display. Please re-open or contact us if you notice anything new!
