### ISSUE TITLE
development roadmap etc

### ISSUE THREAD

**Issue by vncs1880** [muun/apollo#80]
first the praise:
1. I really appreciate the effort you are putting into multi-sig and future-proofing portability via output-descriptors metadata. UX with a great usability/security trade off. IMHO the more of this the better.
2. The lightning stuff is awesome, your approach is working wonders for on boarding new users (myself included), will watch it evolve with excitement.

then the ask:
1. after adopting muun ive been reading your code to learn your development priorities/direction, but do you have a "planned features" roadmap of sort?
2. I wish you had more time so you could strengthen and further modernize muun (i.e. taproot, ux bips, etc), hence I'd like to float **dart/flutter**. I know it's a big one, but idk... maybe someday you want to do a desktop or web portal, it could be easier. i worry about swift/android shenanigans

**Comment by champo** [comment]
Thanks for the praise ❤️  We love to hear that our work is appreciated!

Regarding your questions:
1. We don't have a public roadmap, and we won't have one for a while. What I can assure you is that we'll keep working on making self-custody easier & better.

2. We consciously decided against technologies like flutter. Cross-plataform UI techs are not quite there yet to deliver great UX. We instead opted to do cross platform development for the core of the app. A lot of the complexity, and work, lives there and doesn't require platform specific optimizations (or is easy to do so if needed).

**Comment by vncs1880** [comment]
1. np, pls keep up the good work and don't rush take the time to keep it great! I'm personally excited about being able to lock if my phone is stolen
2. I see, good to know!

**Comment by vncs1880** [comment]
1. np, pls keep up the good work and don't rush take the time to keep it great! I'm personally excited about being able to lock if my phone is stolen
2. I see, good to know!
