### ISSUE TITLE
Add Cuban Peso (CUP) price with free market rate.

### ISSUE THREAD

**Issue by Ventura94** [muun/apollo#96]
Add the price of the Cuban Peso (CUP) with the free market rate, for this they could use the API yadio.io
API de CoinDesk: 1 USD = 25,75 CUP
Yadio API: 1 USD = 185 CUP

**Comment by acrespo** [comment]
Hi there! 

We significantly enhanced our handling exchange rates  and added support for more accurate exchange rates for several currencies, including the Cuban Peso (CUP). You can already see this in both Android and iOS apps without needing to update the app. Hope you like it!
